In [5]:
import PIL
import numpy
from PIL import Image

In [6]:
def filename_crop_array(filename, coords, show=False):
    img = Image.open(filename)
    img = img.crop(coords)
    if show:
        img.show()
    return img.load()

In [7]:
pxa = filename_crop_array("IMG10.JPG", (200, 100, 600, 500))

In [8]:
pxa[100, 100]#ein pinkes pixel

(189, 84, 89)

In [9]:
for x in range(399):
    for y in range(399):
        p = pxa[x, y]
        if (180<= p[0] <= 200) and (75<= p[1] <= 95) and (80<= p[2] <= 100):
            pxa[x, y] = (255, 255, 255)
            

In [10]:
import matplotlib.pyplot
%matplotlib inline
import time

In [11]:
def array_to_img(arr, size):
    img = Image.new("RGB", size)
    for x in range(size[0]):
        for y in range(size[1]):
            #print(arr[x, y])
            img.putpixel((x, y), arr[x, y])
    return(img)

In [25]:
def pxstats(img):#[anz_rot, anz_gruen, anz_blue]
    stat = [0, 0, 0]
    for x in range(0, img.size[0], 4):
        for y in range(0, img.size[1], 4):
            rgb = img.getpixel((x, y))
            r = rgb[0]
            g = rgb[1]
            b = rgb[2]
            if (r-20>= g) and (r-20>= b) and sum(rgb)>200:
                stat[0] +=1
            elif (g-20>= r) and (g-20>= b):
                stat[1] +=1
            elif (b-20>= r) and (b-20>= g):
                stat[2] +=1
        if sum(stat)>100:
            return stat
    return stat

def pxstats2(img):
    pix = numpy.array(img.getdata()).reshape(img.size[0], img.size[1], 3)
    stat = [pix.sum(axis=0), sum(pix[::1]), sum(pix[::2])]
    print(pix.sum(axis=0))
    #print(stat)
    return stat
def pxstats_str(img):
    stat = pxstats2(img)
    r = stat[0]
    g = stat[1]
    b = stat[2]
    if r>g and r>b:
        return "Red"
    elif g>r and g>b:
        return "Green"
    else:
        return "Blue"

def pxshowrgb(img):
    img = img.copy()
    for x in range(img.size[0]):
        for y in range(img.size[1]):
            rgb = img.getpixel((x, y))
            r = rgb[0]
            g = rgb[1]
            b = rgb[2]
            if (r-20>= g) and (r-20>= b) and sum(rgb)>200:
                img.putpixel((x, y), (255, 0, 0))
            elif (g-20>= r) and (g-20>= b):
                img.putpixel((x, y), (0, 255, 0))
            elif (b-20>= r) and (b-20>= g):
                img.putpixel((x, y), (0, 0, 255))
    return img

In [18]:
def clean_analyse_img(filename):
    pxa = filename_crop_array(filename, (200, 100, 600, 500))
    cnt=0
    #for x in range(399):
    #    for y in range(399):
    #        p = pxa[x, y]
    #        if (170<= p[0] <= 210) and (60<= p[1] <= 95) and (70<= p[2] <= 100):
    #            pxa[x, y] = (255, 255, 255)
    #            cnt+=1
    ni = array_to_img(pxa, (400, 400))
    #ni = Image.fromarray(pxa)
    #ni.show()
    print(filename, "\tMain color is:", pxstats_str(ni))
    #return ni
    return 

In [14]:
pxshowrgb(ni).show()

NameError: name 'ni' is not defined

In [ ]:
pxstats(ni)

In [26]:
start = time.perf_counter()
for i in range(10, 45):
    fn = "DSC"+str(i)+".JPG"
    clean_analyse_img(fn)
stop = time.perf_counter()
print((stop-start)/35)

[[60678 63082 67538]
 [60646 63050 67506]
 [60636 63040 67496]
 ..., 
 [56627 58018 62201]
 [56756 58158 62327]
 [56929 58338 62499]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()